In [4]:
import pandas as pd
import os 
from src.results.tidy_data import df_description

In [5]:
df_description = df_description()
df_description

                    instances n_features class_prop
a9a                     32561        123      0.241
analcatdata_lawsuit       264          4      0.072
appendicitis              106          7      0.198
australian                690         14      0.445
backache                  180         31      0.139
...                       ...        ...        ...
yeast1                   1484          8      0.289
yeast3                   1484          8       0.11
yeast4                   1484          8      0.034
yeast5                   1484          8       0.03
yeast6                   1484          8      0.024

[65 rows x 3 columns]

In [6]:
# sort the dataset by the column class_prop
df_description.sort_values(by='class_prop', ascending=False)

             instances n_features class_prop
bupa               345          5       0.49
mammographic       830          4      0.486
splice            1000         60      0.483
mushroom          8124         22      0.482
kr_vs_kp          3196         36      0.478
...                ...        ...        ...
w3a               4912        300      0.029
w4a               7366        300      0.029
w1a               2477        300      0.029
w5a               9888        300      0.028
yeast6            1484          8      0.024

[65 rows x 3 columns]